[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_source = '''
let g:deoplete#enable_at_startup = 1
'''
hook_post_source = '''
let g:deoplete#omni_patterns = {}
'''
[[plugins]]
repo = 'zchee/deoplete-jedi'
on_i = 1
on_ft = 'python'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'basyura/twibill.vim'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'basyura/TweetVim'

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = 'md'

[[plugins]]
repo = 'sy4may0/sosowa.vim'

[[plugins]]
repo = 'kannokanno/previm'
on_ft = 'md'

